name: portfolio
description: My portfolio :)

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.2.3+13

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  delayed_display: ^2.0.0
  flip_card:
    git: https://github.com/BrunoJurkovic/flip_card
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.13
  get: ^4.6.6
  intl: ^0.18.0
  js: ^0.6.4
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  markdown: ^6.0.1
  performance: ^0.1.1
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  slimy_card:
    git: https://github.com/ciriousjoker/SlimyCard-Animated-Flutter-Package.git
  timeline_tile: ^2.0.0
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
  # NOTE: ./fonts/src/README.ME
  uses-material-design: false

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/projects.json

  fonts:
    - family: Exo2
      fonts:
        - asset: fonts/Exo2-Regular.ttf
    - family: BrandIconsMinified
      fonts:
        - asset: fonts/BrandIconsMinified.ttf
    - family: MaterialIconsMinified
      fonts:
        - asset: fonts/MaterialIconsMinified.ttf
    - family: Catamaran
      fonts:
        - asset: fonts/Catamaran/static/Catamaran-Light.ttf
          weight: 200
        - asset: fonts/Catamaran/static/Catamaran-Regular.ttf
          weight: 400
        - asset: fonts/Catamaran/static/Catamaran-Medium.ttf
          weight: 500
