name: portfolio
description: My portfolio :)

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  slimy_card:
    git: https://github.com/CiriousJoker/SlimyCard-Animated-Flutter-Package.git
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.3
  provider: ^5.0.0
  flutter_swiper: ^1.1.6
  intl: ^0.17.0
  flip_card:
    git: https://github.com/CiriousJoker/flip_card.git
  flutter_markdown: ^0.6.2
  shared_preferences: ^2.0.5
  js: ^0.6.3
  delayed_display: ^2.0.0
  json_serializable: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0

flutter:
  # NOTE: ./fonts/src/README.ME
  uses-material-design: false

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/projects.json

  fonts:
    - family: Exo2
      fonts:
        - asset: fonts/Exo2-Regular.ttf
    - family: BrandIconsMinified
      fonts:
        - asset: fonts/BrandIconsMinified.ttf
    - family: MaterialIconsMinified
      fonts:
        - asset: fonts/MaterialIconsMinified.ttf
    - family: Catamaran
      fonts:
        - asset: fonts/Catamaran/static/Catamaran-Light.ttf
          weight: 200
        - asset: fonts/Catamaran/static/Catamaran-Regular.ttf
          weight: 400
        - asset: fonts/Catamaran/static/Catamaran-Medium.ttf
          weight: 500
