/// Flutter icons BrandIconsMinified
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BrandIconsMinified
///      fonts:
///       - asset: fonts/BrandIconsMinified.ttf
///
///
///
import 'package:flutter/widgets.dart';

class BrandIconsMinified {
  BrandIconsMinified._();

  static const _kFontFam = 'BrandIconsMinified';
  static const String? _kFontPkg = null;

  static const IconData adobeaftereffects = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angular = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aurelia = IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c = IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData csharp = IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electron = IconData(0xe972, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData firebase = IconData(0xe9ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flutter = IconData(0xe9bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe9de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googleanalytics = IconData(0xe9f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googlechrome = IconData(0xe9fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googleplay = IconData(0xea0d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googletagmanager = IconData(0xea13, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData java = IconData(0xea85, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData javascript = IconData(0xea86, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xeade, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linux = IconData(0xeae0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData materialdesign = IconData(0xeb07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData node_dot_js = IconData(0xeb6b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData react = IconData(0xec15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sqlite = IconData(0xeca8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tailwindcss = IconData(0xecdc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData typescript = IconData(0xed1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unity = IconData(0xed2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData webpack = IconData(0xed67, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windows = IconData(0xed73, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progressive_web_app = IconData(0xedb5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData babylonjs = IconData(0xedb9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
