/// Flutter icons MaterialIconsMinified
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MaterialIconsMinified
///      fonts:
///       - asset: fonts/MaterialIconsMinified.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MaterialIconsMinified {
  MaterialIconsMinified._();

  static const _kFontFam = 'MaterialIconsMinified';
  static const _kFontPkg = null;

  static const IconData developer_board = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calculator_variant = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_quote_close = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_quote_open = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData open_in_new = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flip_horizontal = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
