name: Deploy

on: [workflow_dispatch]

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Read .fvmrc
        uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Installing dependencies
        run: flutter pub get

      - name: Building for web
        run: flutter build web --release --csp --dart2js-optimization O4 --web-renderer canvaskit

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          cname: philippbauer.me
